### ISSUE TITLE
ボランティアスタッフの募集フォーム

### ISSUE THREAD

**Issue by kimihito** [hackers-champloo/hackers-champloo.github.io#3]
https://github.com/hackers-champloo/hackers-champloo.github.io/commit/8b9721ff3e64419e367b3fa2c6d5cedf55c8e6a6#diff-3f92cef12b597eac104b416bf9f79c56R32 の「こちらからご連絡ください」のリンクがあるといいなーと思うんですけど、該当のリンクってありますでしょうか？

**Comment by k-nishijima** [comment]
このフォームチェックして頂けますか？（FBアカウント必須というのがなんともアレなのですが・・・実運用上仕方ないところ）

問題無さそうならリンク張ります。
http://goo.gl/forms/iEGe9hPPux

**Comment by kimihito** [comment]
問題ないかと思います〜。

**Comment by kimihito** [comment]
対応されたものが上がっているのでCloseします。
